name: watchnext
description: Flutter WatchNext Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.4.1+26

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.5
  chopper: ^6.1.4
  injectable: ^2.1.2
  get_it: ^7.6.0
  json_serializable: ^6.7.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  infinite_scroll_pagination: ^4.0.0
  transparent_image: 2.0.1
  #  google_mobile_ads: ^3.0.0
  app_tracking_transparency: ^2.0.4
  shimmer: ^3.0.0
  intl: 0.19.0
  photo_view: ^0.14.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.0
  age_calculator: ^1.0.0
  get_storage: ^2.1.1
  awesome_notifications: ^0.9.3+1

  #  firebase_analytics: ^10.4.3
  #  flutter_local_notifications: ^14.0.0
  cached_network_image: ^3.4.1
  #  flutter_displaymode: ^0.6.0
  #  google_mobile_ads:
  #    git:
  #      url: https://github.com/SuaMusica/googleads-mobile-flutter.git
  #      path: packages/google_mobile_ads

  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  chopper_generator: ^6.0.3
  injectable_generator: ^2.1.6
  flutter_launcher_icons: ^0.13.1
  json_annotation: ^4.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/wn.png"
  image_path_ios: "assets/ios_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #all assets:

  assets:
    - assets/logo_wide.png
    - assets/logo_tall.png
    - assets/

scripts:
  gen:
    rebuild: "flutter clean && flutter pub get && dart run build_runner build --delete-conflicting-outputs"
    build: "dart run build_runner build"
    watch: "dart run build_runner watch"

  reset: "flutter clean && flutter pub get && flutter precache"


