name: watchnext
description: Flutter WatchNext Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.3.0+24

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  url_launcher: 6.1.10
  cupertino_icons: ^1.0.5
  chopper: ^6.1.1
  injectable: ^2.1.1
  get_it: 7.5.0
  json_serializable: ^6.6.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  infinite_scroll_pagination: ^3.2.0
  transparent_image: 2.0.1
  google_mobile_ads: ^3.0.0
  app_tracking_transparency: 2.0.3
  shimmer: ^2.0.0
  intl: ^0.18.1
  photo_view: ^0.14.0
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.11
  age_calculator: ^1.0.0
  get_storage: ^2.1.1
  firebase_core: ^2.7.1
  firebase_messaging: ^14.5.0
  firebase_analytics: ^10.3.0
#  flutter_local_notifications: ^14.0.0
  cached_network_image: ^3.2.3
#  flutter_displaymode: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  chopper_generator: ^6.0.0
  injectable_generator: ^2.1.1
  flutter_launcher_icons: ^0.10.0
  json_annotation: ^4.5.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/wn.png"
  image_path_ios: "assets/ios_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #all assets:

  assets:
    - assets/logo_wide.png
    - assets/logo_tall.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#flutter clean
#delete /ios/Pods
#delete /ios/Podfile.lock
#flutter pub get
#from inside ios folder: pod install
#flutter run